### ISSUE TITLE
Privacy risks of using this wallet - please improve

### ISSUE THREAD

**Issue by aardbol** [novasamatech/nova-wallet-android#1525]
Your app is leaking personal information, like the user's IP address, to hundreds of external parties by default. The total is now at 173 individual domain names for just some basic usage of the app (not interacting with dapps) according to my analysis.

This causes serious privacy risks due to the following factors:
- the IP address (often) is a personally identifiable piece of information
- knowing someone's IP address can already put them at risk of hacks
- the parties involved are many and are unknown to the user, and the user has no way of limiting the sharing of this information
- not all parties involved have a decent privacy policy, including yourself, because it doesn't mention such

As an IP address is also personally identifiable information, this puts the user of your app at unnecessary risk. While it's guaranteed that the IP is already leaked to so many providers, I'm wondering what other personal information is sent that allows e.g. for profiling the user.

Another concern is the walletconnect Relay server that's being contacted every few seconds. Why are these connections necessary when the walletconnect feature is not being used? It's a good exercise to think about data minimization external sources.

Please provide means for users to be more selective of where their data is being sent to. I noticed that limiting the supported tokens per wallet doesn't affect his leak at all.

**Comment by valentunn** [comment]
Hey! Most of the connections you mention are connections to each blockchain Nova supports. Since each chain uses its own infra it resutls in many unique connections Nova has to establish.
The ability to limit & manage those connections will be provided as a part of "Network managment" update the team is working atm. This will allow users to disabled unneeded chains as well as select their own trusted node for those chains they want to connect to.

The other sources the app makes request to are primarily Coingecko (for prices), and our own infrastracture like history or staking services. Those connections are not yet possible disable nor its planned in the near future as the demand for this is low (you are the first one).

Finally, suggestion about WalletConnect lazy initialization is good one and is actually present in our backglog. We will add it somewhere in the future

**Comment by aardbol** [comment]
It's good to hear these concerns were already part of your plans. I'm looking forward to seeing those features being available

As for the coingecko, I don't see any issue with that personally, as long as it's just price retrieval and no wallet addresses are communicated, which I don't think they are. Besides that, I would find it a useful feature however (although off topic here) to emphasize the utility factor of a token rather than the fiat price value of it. Since now, the fiat price is always shown, it always reminds the user about the monetary value and doesn't much stimulate the utility value by default. Not all of us just care about number  go up, so for us it would be a plus point not to constantly be reminded about fiat value

**Comment by javier3751** [comment]
Gracias por la información buscaré la información necesaria para la privasidad

**Comment by antonkhvorov** [comment]
In upcoming Network management update anyone would be able to disable/enable any network + configure custom nodes for it.
For privacy policy — as Valentin mentioned, Nova does not collect/send any user's personal data even for analytics purposes.
Closing this issue
